/* Autogenerated by bin2c */

#pragma once
#include <stdint.h>

extern char debug_frag[];

extern uint32_t debug_frag_size;

extern char debug_vert[];

extern uint32_t debug_vert_size;

extern char flat_frag[];

extern uint32_t flat_frag_size;

extern char flat_vert[];

extern uint32_t flat_vert_size;

extern char grid_frag[];

extern uint32_t grid_frag_size;

extern char grid_vert[];

extern uint32_t grid_vert_size;

extern char outline_frag[];

extern uint32_t outline_frag_size;

extern char outline_vert[];

extern uint32_t outline_vert_size;

extern char phong_frag[];

extern uint32_t phong_frag_size;

extern char phong_vert[];

extern uint32_t phong_vert_size;

